"use client";

import { useMemo } from "react";
import { useTransactions } from "@/context/TransactionsContext";

import {
  ArrowUpCircle,
  ArrowDownCircle,
  Wallet,
  ShieldCheck,
  FileDown,
  Printer,
  Sparkles,
  TrendingUp,
  TrendingDown,
  AlertTriangle,
} from "lucide-react";

import jsPDF from "jspdf";
import html2canvas from "html2canvas";

export default function AIReport() {
  const { transactions } = useTransactions();

  const income = useMemo(() => {
    return transactions
      .filter((t) => t.type === "income")
      .reduce((sum, t) => sum + Number(t.amount), 0);
  }, [transactions]);

  const expenses = useMemo(() => {
    return transactions
      .filter((t) => t.type === "expense")
      .reduce((sum, t) => sum + Number(t.amount), 0);
  }, [transactions]);

  const savings = income - expenses;

  const savingsRate =
    income === 0 ? 0 : Math.round((savings / income) * 100);

  const categories: Record<string, number> = {};

  transactions
    .filter((t) => t.type === "expense")
    .forEach((t) => {
      categories[t.category] =
        (categories[t.category] || 0) +
        Number(t.amount);
    });

  const sortedCategories = Object.entries(categories).sort(
    (a, b) => b[1] - a[1]
  );

  const highestExpense = sortedCategories[0];

  const healthScore = Math.max(
    0,
    Math.min(
      100,
      Math.round((savings / Math.max(income, 1)) * 100)
    )
  );

  const reportDate = new Date().toLocaleString();

  const reportId =
    "AFA-" +
    new Date().getFullYear() +
    String(new Date().getMonth() + 1).padStart(2, "0") +
    String(new Date().getDate()).padStart(2, "0") +
    "-" +
    Math.floor(Math.random() * 9000 + 1000);

  async function downloadPDF() {
    const report = document.getElementById("financial-report");

    if (!report) return;

    const canvas = await html2canvas(report, {
      scale: 2,
      useCORS: true,
      backgroundColor: "#111827",
    });

    const imgData = canvas.toDataURL("image/png");

    const pdf = new jsPDF("p", "mm", "a4");

    const pdfWidth = pdf.internal.pageSize.getWidth();

    const pageHeight = pdf.internal.pageSize.getHeight();

    const imgWidth = pdfWidth;

    const imgHeight =
      (canvas.height * imgWidth) / canvas.width;

    let heightLeft = imgHeight;

    let position = 0;

    pdf.addImage(
      imgData,
      "PNG",
      0,
      position,
      imgWidth,
      imgHeight
    );

    heightLeft -= pageHeight;

    while (heightLeft > 0) {
      position = heightLeft - imgHeight;

      pdf.addPage();

      pdf.addImage(
        imgData,
        "PNG",
        0,
        position,
        imgWidth,
        imgHeight
      );

      heightLeft -= pageHeight;
    }

    const pages = pdf.getNumberOfPages();

    for (let i = 1; i <= pages; i++) {
      pdf.setPage(i);

      pdf.setFontSize(10);

      pdf.text(
        `AI Finance Analyzer | Report ID: ${reportId}`,
        10,
        pageHeight - 10
      );

      pdf.text(
        `Page ${i} of ${pages}`,
        pdfWidth - 30,
        pageHeight - 10
      );
    }

    pdf.save(`AI_Report_${reportId}.pdf`);
  }

  return (
    <div
      id="financial-report"
      className="space-y-8 bg-background text-foreground"
    >
      {/* HEADER */}

      <div className="rounded-xl border bg-card p-8 shadow-sm">

        <div className="flex items-start justify-between">

          <div>

            <h1 className="text-4xl font-bold">
              📄 AI Financial Report
            </h1>

            <p className="mt-2 text-muted-foreground">
              Generated by AI Finance Analyzer
            </p>

            <div className="mt-5 space-y-1 text-sm text-muted-foreground">

              <p>
                <strong>Report ID:</strong>{" "}
                {reportId}
              </p>

              <p>
                <strong>Generated:</strong>{" "}
                {reportDate}
              </p>

              <p>
                <strong>Total Transactions:</strong>{" "}
                {transactions.length}
              </p>

            </div>

          </div>

          <div className="flex gap-3">

            <button
              onClick={downloadPDF}
              className="flex items-center gap-2 rounded-lg bg-blue-600 px-5 py-3 text-white hover:bg-blue-700"
            >
              <FileDown size={18} />
              Download PDF
            </button>

            <button
              onClick={() => window.print()}
              className="flex items-center gap-2 rounded-lg border px-5 py-3"
            >
              <Printer size={18} />
              Print
            </button>

          </div>

        </div>

      </div>

      {/* SUMMARY CARDS */}

      <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">

        <div className="rounded-xl border bg-card p-6">
          <ArrowUpCircle className="mb-4 text-green-500" size={32} />

          <p className="text-muted-foreground">
            Total Income
          </p>

          <h2 className="mt-2 text-3xl font-bold">
            ₹{income.toLocaleString()}
          </h2>
        </div>

        <div className="rounded-xl border bg-card p-6">
          <ArrowDownCircle className="mb-4 text-red-500" size={32} />

          <p className="text-muted-foreground">
            Total Expenses
          </p>

          <h2 className="mt-2 text-3xl font-bold">
            ₹{expenses.toLocaleString()}
          </h2>
        </div>
                <div className="rounded-xl border bg-card p-6">
          <Wallet className="mb-4 text-blue-500" size={32} />

          <p className="text-muted-foreground">
            Total Savings
          </p>

          <h2 className="mt-2 text-3xl font-bold">
            ₹{savings.toLocaleString()}
          </h2>

          <p className="mt-2 text-sm text-green-500">
            Savings Rate: {savingsRate}%
          </p>
        </div>

        <div className="rounded-xl border bg-card p-6">
          <ShieldCheck className="mb-4 text-emerald-500" size={32} />

          <p className="text-muted-foreground">
            Financial Health
          </p>

          <h2 className="mt-2 text-3xl font-bold">
            {healthScore}/100
          </h2>

          <div className="mt-4 h-3 w-full overflow-hidden rounded-full bg-zinc-700">

            <div
              className="h-full rounded-full bg-green-500"
              style={{
                width: `${healthScore}%`,
              }}
            />

          </div>

        </div>

      </div>

      {/* EXECUTIVE SUMMARY */}

      <div className="rounded-xl border bg-card p-8 shadow-sm">

        <div className="flex items-center gap-3">

          <Sparkles className="text-yellow-400" />

          <h2 className="text-2xl font-bold">
            Executive Summary
          </h2>

        </div>

        <p className="mt-6 leading-8 text-muted-foreground">

          This report was automatically generated using the uploaded
          transaction history. It summarizes your income,
          expenditure, savings performance and spending behaviour
          to provide an overall picture of your financial health.

        </p>

      </div>

      {/* ANALYSIS */}

      <div className="grid gap-6 lg:grid-cols-2">

        <div className="rounded-xl border bg-card p-8">

          <div className="flex items-center gap-3">

            <TrendingUp className="text-green-500" />

            <h2 className="text-2xl font-bold">
              Income Analysis
            </h2>

          </div>

          <p className="mt-6">
            Total Income
          </p>

          <h3 className="mt-2 text-3xl font-bold">
            ₹{income.toLocaleString()}
          </h3>

          <p className="mt-6 leading-7 text-muted-foreground">

            Your income comfortably supports your current
            expenditure. Maintaining this income level while
            controlling expenses will improve long-term
            financial stability.

          </p>

        </div>

        <div className="rounded-xl border bg-card p-8">

          <div className="flex items-center gap-3">

            <TrendingDown className="text-red-500" />

            <h2 className="text-2xl font-bold">
              Expense Analysis
            </h2>

          </div>

          <p className="mt-6">
            Total Expenses
          </p>

          <h3 className="mt-2 text-3xl font-bold">
            ₹{expenses.toLocaleString()}
          </h3>

          <p className="mt-6 leading-7">

            Highest Expense Category:

            <strong>

              {" "}
              {highestExpense?.[0] ?? "N/A"}

            </strong>

          </p>

          <p className="mt-2 text-muted-foreground">

            Amount:

            <strong>

              {" "}
              ₹{highestExpense?.[1]?.toLocaleString() ?? 0}

            </strong>

          </p>

        </div>

      </div>

      {/* AI INSIGHTS */}

      <div className="rounded-xl border bg-card p-8">

        <div className="flex items-center gap-3">

          <AlertTriangle className="text-orange-500" />

          <h2 className="text-2xl font-bold">
            AI Financial Insights
          </h2>

        </div>

        <div className="mt-6 space-y-4">

          <div className="rounded-lg border p-4">

            ✅ Your savings rate is

            <strong>
              {" "}
              {savingsRate}%
            </strong>

            , indicating

            <strong>

              {healthScore > 60
                ? " strong financial discipline."
                : " room for improvement."}

            </strong>

          </div>

          <div className="rounded-lg border p-4">

            ✅ Largest spending category:

            <strong>

              {" "}
              {highestExpense?.[0] ?? "N/A"}

            </strong>

          </div>

          <div className="rounded-lg border p-4">

            ✅ Income exceeds expenses by

            <strong>

              {" "}
              ₹{savings.toLocaleString()}

            </strong>

          </div>

        </div>

      </div>
          {/* RECOMMENDATIONS */}

      <div className="rounded-xl border bg-card p-8">

        <h2 className="text-2xl font-bold">
          🎯 AI Recommendations
        </h2>

        <div className="mt-6 space-y-4">

          <div className="rounded-lg border-l-4 border-green-500 bg-green-500/10 p-4">
            <h3 className="font-semibold text-green-500">
              Investment
            </h3>

            <p className="mt-2 text-muted-foreground">
              Consider investing a portion of your monthly savings into
              mutual funds, index funds, or fixed-income investments to
              build long-term wealth.
            </p>
          </div>

          <div className="rounded-lg border-l-4 border-yellow-500 bg-yellow-500/10 p-4">
            <h3 className="font-semibold text-yellow-500">
              Expense Control
            </h3>

            <p className="mt-2 text-muted-foreground">
              Monitor your highest spending category regularly and try to
              reduce discretionary expenses by 10–15% each month.
            </p>
          </div>

          <div className="rounded-lg border-l-4 border-blue-500 bg-blue-500/10 p-4">
            <h3 className="font-semibold text-blue-500">
              Emergency Fund
            </h3>

            <p className="mt-2 text-muted-foreground">
              Maintain an emergency fund covering at least 3–6 months of
              essential expenses for better financial security.
            </p>
          </div>

        </div>

      </div>

      {/* OVERALL HEALTH */}

      <div className="rounded-xl border bg-card p-8">

        <h2 className="text-2xl font-bold">
          📈 Overall Financial Health
        </h2>

        <div className="mt-8">

          <div className="h-6 overflow-hidden rounded-full bg-zinc-700">

            <div
              className="h-full rounded-full bg-green-500 transition-all duration-700"
              style={{
                width: `${healthScore}%`,
              }}
            />

          </div>

          <div className="mt-6 flex items-center justify-between">

            <span className="text-lg font-semibold">
              Financial Score
            </span>

            <span className="text-3xl font-bold text-green-500">
              {healthScore}/100
            </span>

          </div>

          <p className="mt-4 leading-7 text-muted-foreground">

            {healthScore >= 80
              ? "Excellent financial position. Continue your current saving and spending habits."
              : healthScore >= 60
              ? "Good financial condition. A few spending optimizations can improve your score."
              : "Your financial health needs attention. Focus on increasing savings and reducing unnecessary expenses."}

          </p>

        </div>

      </div>

      {/* FOOTER */}

      <div className="rounded-xl border bg-card p-6 text-center">

        <h3 className="text-lg font-semibold">
          AI Finance Analyzer
        </h3>

        <p className="mt-2 text-sm text-muted-foreground">
          This report was automatically generated using your uploaded
          transaction data and AI-powered financial analysis.
        </p>

        <p className="mt-4 text-xs text-muted-foreground">
          Report ID: {reportId}
        </p>

        <p className="text-xs text-muted-foreground">
          Generated on {reportDate}
        </p>

      </div>

    </div>
  );
}